name: Build and deploy to CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
    	  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
	  AWS_SECREY_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
	  AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --exclude '*' --include 'index.html' 
      env:
        AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
      
  - name: Invalidate CloudFront Cache
  uses: chetan/invalidate-cloudfront-action@master
  env:
  DISTRIBUTION: ${{ secrets.DEV_AWS_DISTRIBUTION_ID }}
  PATHS: '/index.html'
	continue-on-error" true